### ISSUE TITLE
M3DRef-CLIP on Scanrefer Test Benchmark

### ISSUE THREAD

**Issue by ayushjain1144** [3dlg-hcvc/M3DRef-CLIP#10]
Hi, 

Thank you for your awesome work!

For scanrefer benchmark submission, do you train on a combination of train+val split or only the train split? I am asking because in scannet benchmarks, training on train+val is a common practice, but not sure what people do in referential grounding benchmarks. Also are there any other details/tricks for test set submission, or simply exporting the data with the provided checkpoint trained on train set?

Thank you!

**Comment by eamonn-zh** [comment]
Hi @ayushjain1144, our test set benchmark result is only trained on the train split. There is no trick for test set submission, just do the inference using either our provided checkpoint or your retrained one, and submit it. You should be able to reproduce our results.

**Comment by ayushjain1144** [comment]
Thank you :)
