### ISSUE TITLE
Visualization Script

### ISSUE THREAD

**Issue by haomengz** [3dlg-hcvc/M3DRef-CLIP#13]
Hi, 

Thanks for the nice work! I am wondering whether you could provide the visualization scripts for your model. For example, the script to generate the sub-figures in your Figure 6, Figure 10 and Figure 12. Thanks!

**Comment by eamonn-zh** [comment]
Hi @haomengz, sorry we don't have a plan to release the visualization script. But I can share with you how we generated those figures. We used Open3D to visualize scenes and axis-aligned bounding boxes, then we just took screenshots. It should be easy to implement.
