### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by victor-cilay** [3dlg-hcvc/M3DRef-CLIP#14]
Encountered this error，everything is freshly clone from this repo

“RuntimeError: CUDA error: an illegal memory access was encountered                                                                                                                                   
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                                              
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                                                                                               
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.       ”

**Comment by eamonn-zh** [comment]
Hello @victor-cilay, are you using our original experiment configs? Please first make sure your GPU memory is enough, since this error could happen due to the CUDA out-of-memory error.
