### ISSUE TITLE
Proposal filtering for PointGroup

### ISSUE THREAD

**Issue by tony10101105** [3dlg-hcvc/M3DRef-CLIP#17]
Hi,

I noticed that you chose not to filter the PointGroup proposals by nms or proposal scores. Have you tried that before? I wonder about the effects of proposal filtering, such as the final performance going down, but early-stage performance being high.

Best,
Tony

**Comment by eamonn-zh** [comment]
Hi @tony10101105, unfortunately, we haven't tried applying NMS for the PointGroup proposals, but we sort proposals based on the confidence scores and pick the top 128.
