### ISSUE TITLE
Train on ScanRefer dataset

### ISSUE THREAD

**Issue by yihang-xdu** [3dlg-hcvc/M3DRef-CLIP#19]
Dear Authors,
Thanks for your great work! When I execute the command "python train.py data=scanrefer experiment_name=scanrefer +detector_path=checkpoints/PointGroup_ScanNet.ckpt Model.net work. The detector. Use_gt_proposal = True ", appear the following error:

File "/data1/zyh/M3DRef-CLIP/m3drefclip/data/dataset/scanrefer.py", line 35, in _load_language_data
"eval_type": item["eval_type"],
KeyError: 'eval_type'

File "M3DRef - CLIP/dataset/scanrefer/metadata/ScanRefer_filtered_train json" does not contain 'eval_type'.  
I noticed that when training on the nr3d dataset, its 'eval_type' value is added as an extra in the code.[https://github.com/3dlg-hcvc/M3DRef-CLIP/blob/babfcc4b4f06bb8ce1471513095a1c80acc0edb5/m3drefclip/data/dataset/nr3d.py#L41-L50](url). 
So I would like to ask whether it is necessary to add an extra 'eval_type' as when training on the nr3d data set?

**Comment by eamonn-zh** [comment]
Hi @yihang-xdu , I think you skipped **step 2** for ScanRefer dataset preprocessing (please follow [this instruction](https://github.com/3dlg-hcvc/M3DRef-CLIP?tab=readme-ov-file#scanrefer-dataset)). The script will add the `eval_type` for you.
