### ISSUE TITLE
CLIP text model output. How/Why two outputs word_features & sentence features?

### ISSUE THREAD

**Issue by kochsebastian** [3dlg-hcvc/M3DRef-CLIP#4]
I was wondering why you are expecting two outputs when calling `word_features, sentence_features = self.clip_model.encode_text(clip_tokens)` [here](https://github.com/3dlg-hcvc/M3DRef-CLIP/blob/b697586f377784ef9399e4a2a7591d5058136485/m3drefclip/model/language_module/clip_word_encoder.py#L30C9-L30C84)

As far as I understand, you are using a vanilla clip model which outputs only one embedding for `clip_model.encode_text()`. 
Evidently this cant be the case since you are expecting two different embeddings. So where did you implement the custom functionality to get two embeddings from  `encode_text()`?

**Comment by Xiaolong-RRL** [comment]
Hi, see [here](https://github.com/eamonn-zh/CLIP/commit/0c9b873ea68db4b97d35f1f452b68c334763d157)

**Comment by eamonn-zh** [comment]
Yes, exactly. @Xiaolong-RRL Thank you for helping answer it!
