### ISSUE TITLE
Could not append to config. An item is already at 'ckpt_path'. Either remove + prefix: 'ckpt_path=M3DRef-CLIP_ScanRefer.ckpt' Or add a second + to add or override 'ckpt_path': '++ckpt_path=M3DRef-CLIP_ScanRefer.ckpt'

### ISSUE THREAD

**Issue by Andy20178** [3dlg-hcvc/M3DRef-CLIP#8]
Hello, I followed the readme and did all of it, when I ran the command:
python test.py data=scanrefer data.inference.split=val +ckpt_path=M3DRef-CLIP_ScanRefer.ckpt pred_path=output
The error is:
Could not append to config. An item is already at 'ckpt_path'. Either remove + prefix: 'ckpt_path=M3DRef-CLIP_ScanRefer.ckpt' Or add a second + to add or override 'ckpt_path': '++ckpt_path=M3DRef-CLIP_ScanRefer.ckpt'

**Comment by eamonn-zh** [comment]
Hi @Andy20178,
Sorry for this typo, please remove the "+" before ckpt_path since this flag is already in the yaml. I just updated the README, please run:
`python test.py data=scanrefer data.inference.split=val ckpt_path=M3DRef-CLIP_ScanRefer.ckpt pred_path=output`
